# Generated by Django 5.2 on 2025-04-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_closed', models.BooleanField(default=False, verbose_name='Сайт закрыт')),
                ('maintenance_message', models.TextField(default='Сайт временно недоступен. Мы скоро вернёмся!', verbose_name='Сообщение для посетителей')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
