# Generated by Django 5.2 on 2025-04-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
